const walletInfoList = [
  {
    link: "https://ethereum.org/static/51dd40a19a238210b292190522d3c63a/bfa43/ledger.webp",
    name: "Ledger",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://www.ledger.com/",
  },
  {
    link: "https://ethereum.org/static/463b977caa0282f5c1ff85daa2100852/bfa43/trust.webp",
    name: "Trust Wallet",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: null,
    web: null,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://trustwallet.com/",
  },
  {
    link: "https://ethereum.org/static/f541df14fca86543040c113725b5bd1a/7a26d/metamask.webp",
    name: "MetaMask",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: null,
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://metamask.io/",
  },
  {
    link: "https://ethereum.org/static/0cb605dd3829711750f94bfc0ac0cb69/bfa43/opera.webp",
    name: "Opera Browser",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: null,
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://www.opera.com/tr/crypto/next",
  },
  {
    link: "https://ethereum.org/static/3f65dd8f26f2ca234b8b524e1b048660/bfa43/loopring.webp",
    name: "Loopring",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://loopring.io/",
  },
  {
    link: "https://ethereum.org/static/a87bfa3a27f1d51538e3f4bc0e9248d8/bfa43/alpha.webp",
    name: "Alpha Wallet",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: null,
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://alphawallet.com/",
  },
  {
    link: "https://ethereum.org/static/41a2bcdbb7ef3803605ed6c0afbe0337/bfa43/keystone.webp",
    name: "Keystone",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: null,
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://keyst.one/",
  },
  {
    link: "https://ethereum.org/static/a918352b37b4f847099e555e0964ac78/bfa43/coinbase.webp",
    name: "Coinbase Wallet",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: null,
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://www.coinbase.com/wallet",
  },
  {
    link: "https://ethereum.org/static/c74e9d8e18d22917a48c4a4a5f79ff41/bfa43/enjin.webp",
    name: "Enjin",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: null,
    web: null,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://enjin.io/products/wallet",
  },
  {
    link: "https://ethereum.org/static/8c45056b7cdd009af22c30dabc573825/bfa43/mycrypto.webp",
    name: "My Crypto",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: null,
    hardware: null,
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://www.mycrypto.com/",
  },
  {
    link: "https://ethereum.org/static/dd1300798d3d2ce87e6b65153f278cc8/bfa43/myetherwallet.webp",
    name: "myEtherWallet",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: null,
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://www.myetherwallet.com/",
  },
  {
    link: "https://ethereum.org/static/2d82f676d911a95e3be88d58d9450522/caa3b/linen.webp",
    name: "linen",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: null,
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://linen.app/",
  },
  {
    link: "https://ethereum.org/static/ae3b6cfa8c1cb78ede0f9f245f6c1aeb/bfa43/mathwallet.webp",
    name: "Math Wallet",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://mathwallet.org/en-us/",
  },
  {
    link: "https://ethereum.org/static/1451fcccfdf060df88cdd664c0766e8e/bfa43/argent.webp",
    name: "Argent",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: null,
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://www.argent.xyz/",
  },
  {
    link: "https://ethereum.org/static/a0f2d791562dacf6333ee1ef577ace2f/bfa43/bitkeep.webp",
    name: "Bitkeep Wallet",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://bitkeep.com/",
  },
  {
    link: "https://ethereum.org/static/81905ce6aa3a09e2bedc9081d5502f04/bfa43/imtoken.webp",
    name: "imToken",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://token.im/",
  },
  {
    link: "https://ethereum.org/static/0f07b180b56256dc0d72e5be4a9d1878/bfa43/bitcoindotcom.webp",
    name: "Bitcoin.com Wallet",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://wallet.bitcoin.com/",
  },
  {
    link: "https://ethereum.org/static/0cb605dd3829711750f94bfc0ac0cb69/bfa43/opera.webp",
    name: "Opera Browser",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://www.opera.com/tr/crypto/next",
  },
  {
    link: "https://ethereum.org/static/463b977caa0282f5c1ff85daa2100852/bfa43/trust.webp",
    name: "Trust Wallet",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: null,
    web: "https://twemoji.maxcdn.com/2/svg/1f310.svg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
    golink: "https://trustwallet.com/",
  },
  {
    link: "https://ethereum.org/static/012c58943ee1968ea3a05943bf6dea05/bfa43/multis.webp",
    name: "Multis",
    mobilew: "Mobile",
    webw: "Web",
    hardwarew: "Hardware",
    mobile: "https://twemoji.maxcdn.com/2/svg/1f4f1.svg",
    hardware: "https://twemoji.maxcdn.com/2/svg/1f4bd.svg",
    web: null,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus erat neque, blandit et libero eget, semper facilisis dolor. Fusce vel ligula id nisl malesuada ornare. Donec lobortis porta elit, vel faucibus purus blandit non.",
  },
];

export default walletInfoList;
